apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-es0
spec:
    capacity:
      storage: 90Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /log/efk/pv-es0/
      server: 10.2.2.8
