apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-es1
spec:
    capacity:
      storage: 90Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /log/efk/pv-es1/
      server: 10.2.2.8
